<table id="<?php echo $this->getId(); ?>" class="<?php echo $this->getStyleClass(); ?>" style="<?php echo $this->getInlineStyle(); ?>">
	<thead>
		<tr>
		<?php foreach ($this->getColumns() as $column) { ?>
			<th style="width: <?php echo $column->getWidth(); ?>;"><?php echo $column->getLabel(); ?></th>
		<?php } ?>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->getDataProvider() as $item) { ?>
		<tr>
			<?php foreach ($this->getColumns() as $column) { ?>
			<td><?php echo $column->getContent($item); ?></td>
			<?php } ?>
		</tr>
	<?php } ?>
	</tbody>
	<?php if ($this->willDisplayLabelsOnFooter()) { ?>
	<tfoot>
		<tr>
		<?php foreach ($this->getColumns() as $column) { ?>
			<th style="width: <?php echo $column->getWidth(); ?>;"><?php echo $column->getLabel(); ?></th>
		<?php } ?>
		</tr>
	</tfoot>
	<?php } ?>
</table>